# Generated by Django 4.1.4 on 2022-12-21 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task0model',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
